<?php

declare(strict_types=1);

namespace MsgPhp\Domain\Tests\Infra\InMemory;

use MsgPhp\Domain\{DomainId, DomainIdentityHelper};
use MsgPhp\Domain\Infra\InMemory\{DomainEntityRepositoryTrait, DomainIdentityMapping, ObjectIdentityMap};
use MsgPhp\Domain\Tests\AbstractDomainEntityRepositoryTraitTest;
use MsgPhp\Domain\Tests\Fixtures\{DomainEntityRepositoryTraitInterface, Entities};

final class DomainEntityRepositoryTraitTest extends AbstractDomainEntityRepositoryTraitTest
{
    protected static $supportsAutoGeneratedIds = false;

    /** @var ObjectIdentityMap */
    private static $identityMap;

    protected function setUp(): void
    {
        self::$identityMap = new ObjectIdentityMap();
    }

    protected function tearDown(): void
    {
        self::$identityMap = null;
    }

    protected static function createRepository(string $class): DomainEntityRepositoryTraitInterface
    {
        $mapping = [];
        foreach (self::$entityTypes as $knownClass) {
            $mapping[$knownClass] = $knownClass::getIdFields();
        }
        $identityHelper = new DomainIdentityHelper(new DomainIdentityMapping($mapping));

        /** @psalm-suppress InaccessibleMethod */
        return new class($class, $identityHelper, self::$identityMap) implements DomainEntityRepositoryTraitInterface {
            use DomainEntityRepositoryTrait {
                doFindAll as public;
                doFindAllByFields as public;
                doFind as public;
                doFindByFields as public;
                doExists as public;
                doExistsByFields as public;
                doSave as public;
                doDelete as public;
            }
        };
    }

    protected static function flushEntities(iterable $entities): void
    {
        foreach ($entities as $entity) {
            $testEntity = $entity instanceof Entities\TestDerivedEntity ? $entity->entity : $entity;

            if ($testEntity instanceof Entities\TestEntity && $testEntity->getId()->isEmpty()) {
                $testEntity->setId(new DomainId(bin2hex(random_bytes(32))));
            }

            self::$identityMap->persist($entity);
        }
    }
}
