#!/usr/bin/env php
<?php

namespace MsgPhp;

use MsgPhp\Domain\Event\DomainEventInterface;
use Twig\Environment;
use Twig\Loader\ArrayLoader;

if (!is_file('vendor/autoload.php')) {
    echo "\e[34mInstalling dependencies\e[0m\n";
    passthru('composer install --prefer-dist --quiet', $return);
    if (0 !== $return) {
        echo "\e[41mFailed\e[0m\n";
        exit($return);
    }
}

require 'vendor/autoload.php';

function file_to_class(string $file): string
{
    $dir = dirname($file, substr_count($file, \DIRECTORY_SEPARATOR) - 1);
    $ns = key(json_decode(file_get_contents($dir.'/composer.json'), true)['autoload']['psr-4']);

    return str_replace('/', '\\', str_replace($dir.\DIRECTORY_SEPARATOR, $ns, substr($file, 0, -4)));
}

function load_template(string $file): array
{
    extract(['msgphp' => global_vars()]);
    $template = include $file;

    return $template;
}

function global_vars(): array
{
    static $vars;
    if (null !== $vars) {
        return $vars;
    }

    $vars = ['domains' => [], 'bundles' => []];
    foreach (glob('src/*/composer.json') as $file) {
        $package = json_decode(file_get_contents($file));
        $entry = ['path' => dirname($file), 'package' => $package];

        if ('-bundle' === substr($package->name, -7)) {
            $vars['bundles'][$package->name] = $entry;
            continue;
        }

        $vars['domains'][$package->name] = $entry + [
            'entities' => array_map(function (string $file): string {
                return file_to_class($file);
            }, glob(dirname($file).'/Entity/*.php')),
            'entity_fields' => array_map(function (string $file): string {
                return file_to_class($file);
            }, glob(dirname($file).'/Entity/Fields/*Field.php')),
            'entity_features' => array_map(function (string $file): string {
                return file_to_class($file);
            }, array_filter(glob(dirname($file).'/Entity/Features/*.php'), function (string $file): bool {
                return 'Abstract' !== substr(basename($file), 0, 8);
            })),
            'identifiers' => array_map(function (string $file): array {
                return [
                    'class' => $class = file_to_class($file),
                    'scalar' => class_exists($scalar = substr($class, 0, -9)) ? $scalar : null,
                    'uuid' => class_exists($uuid = 'MsgPhp\\'.basename(dirname($file)).'\\Infra\\Uuid\\'.basename($file, 'Interface.php')) ? $uuid : null,
                ];
            }, glob(dirname($file).'/*IdInterface.php')),
            'repositories' => array_map(function (string $file): string {
                return file_to_class($file);
            }, glob(dirname($file).'/Repository/*RepositoryInterface.php')),
            'commands' => array_map(function (string $file): string {
                return file_to_class($file);
            }, glob(dirname($file).'/Command/*Command.php')),
            'events' => array_filter(array_map(function (string $file): string {
                return file_to_class($file);
            }, glob(dirname($file).'/Event/*Event.php')), function (string $class): bool {
                return !is_subclass_of($class, DomainEventInterface::class);
            }),
            'domain_events' => array_filter(array_map(function (string $file): string {
                return file_to_class($file);
            }, glob(dirname($file).'/Event/{*,Domain/*}Event.php', \GLOB_BRACE)), function (string $class): bool {
                return is_subclass_of($class, DomainEventInterface::class);
            }),
        ];
    }

    ksort($vars['domains']);
    ksort($vars['bundles']);

    $vars['domains'] = [$k = 'msgphp/domain' => $vars['domains'][$k]] + $vars['domains'];

    return $vars;
}

$templates = $templateVars = [];
foreach (glob('docs/.refs/*.php') as $reference) {
    $template = load_template($reference);
    $templates[$name = basename($reference, '.php')] = array_shift($template);
    $templateVars[$name] = $template;
}

$twig = new Environment(new ArrayLoader($templates));
$twig->addGlobal('msgphp', global_vars());
$replacements = [];

foreach (array_keys($templates) as $template) {
    $from = '~'.preg_quote($start = '<!--ref-start:'.$template.'-->', '~').'.*'.preg_quote($end = '<!--ref-end:'.$template.'-->', '~').'~s';
    $to = $start."\n".$twig->render($template, $templateVars[$template]).$end;
    $replacements[$from] = $to;
}

foreach (glob('docs/{*,**/*}.md', \GLOB_BRACE) as $file) {
    file_put_contents($file, preg_replace(array_keys($replacements), array_values($replacements), file_get_contents($file)));
}

echo "\e[34mCompiled templates\e[0m\n";
echo ' * '.implode("\n * ", array_keys($templates))."\n";
